// IntelligentCustomerService/IntelligentCustomerService/web/src/layout/components/header/components/MenuCollapse.vue
<template>
  <n-icon size="20" cursor-pointer @click="appStore.switchCollapsed">
    <icon-mdi:format-indent-increase v-if="appStore.collapsed" />
    <icon-mdi:format-indent-decrease v-else />
  </n-icon>
</template>

<script setup>
import {useAppStore} from '@/store'

const appStore = useAppStore()
</script>

// IntelligentCustomerService/IntelligentCustomerService/web-react/src/components/layout/MenuCollapse.tsx
import React from 'react'
import {Icon} from '@iconify/react'
import {useAppStore} from '../../store/app'

/**
 * 菜单折叠按钮组件 - 对应Vue版本的MenuCollapse.vue
 *
 * 功能特性：
 * 1. 图标大小20px，鼠标指针样式
 * 2. 折叠状态显示展开图标（format-indent-increase）
 * 3. 展开状态显示折叠图标（format-indent-decrease）
 * 4. 点击切换侧边栏折叠状态
 */
const MenuCollapse: React.FC = () => {
  const { collapsed, toggleCollapsed } = useAppStore()

  return (
    <Icon
      icon={collapsed ? 'mdi:format-indent-increase' : 'mdi:format-indent-decrease'}
      style={{ fontSize: '20px', cursor: 'pointer' }}
      onClick={toggleCollapsed}
    />
  )
}

export default MenuCollapse
